### ISSUE TITLE
WinkTests does not compile on Swift 6.2.4: sending-risks-data-race in two phased-delivery harnesses

### ISSUE THREAD

**Issue by zjlgdx** [xrf9268-hue/hotapp-clone#448]
`swift build --build-tests` and `swift test` fail to compile the `WinkTests` target under **Swift 6.2.4** (`swiftlang-6.2.4.1.4`, `arm64-apple-macosx15.0`). The app target itself builds; only the test target is affected.

Reproduced on a clean `.build` at `main@a7672dce` with no working-tree changes, and again on a branch that touches zero Swift files.

## Failures

Two sites, one root cause, 28 diagnostics total (the same errors repeat per test-target compilation job):

```
Tests/WinkTests/HoldGestureArbiterTests.swift:186:55: error: sending 'deliveries' risks causing data races [#SendingRisksDataRace]
  note: 'deliveries' is captured by a main actor-isolated closure. main actor-isolated uses in closure may race against later nonisolated uses
  note: access can happen concurrently

Tests/WinkTests/PhasedKeyDeliveryTests.swift:61:61: error: sending 'phasedDeliveries' risks causing data races [#SendingRisksDataRace]
```

Both follow the same shape: a `nonisolated(unsafe) var` counter is mutated inside a closure the compiler infers as `@MainActor`-isolated, then read from a nonisolated `#expect(...)`. Swift 6.2's region-based isolation now treats the capture as a `sending` violation where the earlier toolchain accepted it.

```swift
nonisolated(unsafe) var deliveries = 0
box.setPhasedKeyObserver { _, _ in deliveries += 1 }
...
#expect(deliveries == 0)
```

## Why this matters

- `swift test` is the repository's primary local gate and the PR template's first Testing item. Nobody on a current Xcode toolchain can honestly check that box for **any** PR, regardless of what the PR changes.
- CI on `macos-15` was last green on 2026-07-24 (`a7672dce`). GitHub rolls Xcode forward on that image, so this is a latent CI break, not merely a local inconvenience.
- `nonisolated(unsafe)` is an escape hatch that suppresses the checker, not a fix. These counters really are written on one isolation domain and read on another; the toolchain upgrade exposed a pre-existing test-harness race rather than inventing one.

## Scope

Make the two harnesses express the actual synchronization instead of asserting it away. Options to evaluate, in preference order:

1. Give each test a small `final class Recorder: @unchecked Sendable` (or an actor) with an internal lock, so the write and the read share one well-defined domain.
2. Mark the test functions `@MainActor` so the closure and the `#expect` read are in the same isolation domain — only if the production callback genuinely delivers on the main actor. `EventTapBox.onHyperHoldEvent` explicitly does **not** (AGENTS.md: "fires on the tap thread outside the lock"), so verify per call site rather than applying this blanket.
3. Keep `nonisolated(unsafe)` only where the test provably runs the closure synchronously on the calling thread before the read, and add a comment recording that proof.

Sweep the whole test target for the same pattern rather than fixing only the two sites the compiler happened to reach first — compilation stops early, so more may be hiding behind these.

## Acceptance criteria

- [ ] `swift build`, `swift build --build-tests`, and `swift test` all succeed on Swift 6.2.4 with no warnings introduced.
- [ ] The chosen fix does not weaken what each test asserts; hold/tap arbitration and phased-delivery ordering coverage stay equivalent.
- [ ] A repository-wide grep for `nonisolated(unsafe)` in `Tests/` is triaged, and every remaining use carries a comment justifying it.
- [ ] The toolchain version this was fixed against is recorded in the PR, and CI is confirmed green on the head commit.
- [ ] No production `Sources/Wink` behavior change; this is test-harness work.

## Environment

```
swift-driver version: 1.127.15 Apple Swift version 6.2.4 (swiftlang-6.2.4.1.4 clang-1700.6.4.2)
Target: arm64-apple-macosx15.0
```
